### ISSUE TITLE
Support for Docker push-to-group.

### ISSUE THREAD

**Issue by CMYanko** [AdaptiveConsulting/nexus-casc-plugin#11]
This is anew feature in 3.27 and is PRO only. There is a new field in the docker group to associate the group with a docker-hosted registry so the user can push to the group and not have two ports for docker. I realize you don't have a license to test the PRO features but I've alerted our London team. Either I can do the testing or we can explore a trial license for you.

FYI - I'm trying to get the project setup in VSCode so I can self service more but I'm a lousy developer ;-)

**Comment by bdellegrazie** [comment]
Hi @CMYanko,

For this to be possible, I need to know what the property name(s) is on the docker-group to map the docker-hosted repo.
Access to the underlying APIs should not be necessary in this specific case as properties are just mapped by name here.
If you can tell me what the property name is please - we can simply document it and this will be complete.

Thanks in advance,

Brett

**Comment by CMYanko** [comment]
Looking into it

**Comment by CMYanko** [comment]
I was out last week, tracking down an answer now ;-)

**Comment by CMYanko** [comment]
Got it! It is WriteMember and this config is working for me:

- name: docker-all
      online: true
      recipeName: docker-group
      attributes:
        docker:
          forceBasicAuth: false  # Each repo uses its own setting
          v1Enabled: false
          #PRO ONLY, otherwise set a port on the 'hosted' registry
          httpPort: 5000   # Uncomment to activate
          #httpsPort: 8083  # Requires Nexus Jetty be configured to use SSL Certificates
        storage:
          blobStoreName: docker
          strictContentTypeValidation: true
        group:
          memberNames:
            - "docker-hosted"
            - "docker-proxy"
          WriteMember: docker-hosted

**Comment by bdellegrazie** [comment]
Not sure if its case sensitive @CMYanko - could you test `writeMember` as well to see if the configuration winds up the same please?

**Comment by CMYanko** [comment]
Just realized my 'test' was bogus. re-testing now, this time for real ;-)

**Comment by CMYanko** [comment]
Ok, I miss interpreted what the product team told me but have it working now with these entries:

        group:
          memberNames:
            - "docker-hosted"
            - "docker-proxy"
          # PRO ONLY - set which hosted repo to pass a 'push' to
          groupWriteMember: docker-hosted
