### ISSUE TITLE
yum/apt/raw recipes?

### ISSUE THREAD

**Issue by greasewizard** [AdaptiveConsulting/nexus-casc-plugin#13]
Hello,

I was curious if there is support for yum/apt/raw file/proxy/group recipes? If so, can there be examples added?

**Comment by bdellegrazie** [comment]
@greasewizard not yet - but if you add them as a PR, I'll include them.

**Comment by bdellegrazie** [comment]
@greasewizard the latest `default-nexus.yml` has examples for apt, raw and yum.
