### ISSUE TITLE
reload configuration when yaml file changed

### ISSUE THREAD

**Issue by shurikg** [AdaptiveConsulting/nexus-casc-plugin#20]
Hi,

How can I apply the changes in yaml file without to restart the nexus?

**Comment by bdellegrazie** [comment]
Hi @shurikg, I'm afraid you can't. The plugin performs actions at certain points during the Nexus startup sequence so Nexus must be restarted for changes to take effect.

You can initiate a restart via the Life cycle API if that helps, but I suspect it doesn't.
