### ISSUE TITLE
cleanup policy with "published before"

### ISSUE THREAD

**Issue by Aleks3050** [AdaptiveConsulting/nexus-casc-plugin#3]
Hi, @mattbarrett !
In Readme I see only example with lastDownloaded option for cleanup policy.
If I need option published before, what I need to configure?
I try to use:
            criteria:
              publishedBefore: 864000
and
            criteria:
              published: 864000

But no effect. Can you add example to README?
Thank you!

**Comment by Aleks3050** [comment]
@bdellegrazie tag you)

**Comment by bdellegrazie** [comment]
@Aleks3050 the key is `lastBlobUpdated`
