### ISSUE TITLE
Auto bumping the version for the newest nexus oss release

### ISSUE THREAD

**Issue by IreshMM** [AdaptiveConsulting/nexus-casc-plugin#38]
Is there a way to bump the version as new releases for nexus oss comes (of course only after an automated check of API compatibility)

Just a question: would the latest version of nexus oss (3.44.0-01) be compatible with the current version (3.41.1-01.0) of the plugin? Do the minor changes to nexus oss break the compatibility? (as in this case). If not let's update the README on that.

**Comment by bdellegrazie** [comment]
In general it should be fine to try, I try to use the stable APIs but nothing is guaranteed.
