### ISSUE TITLE
cleanup policy format

### ISSUE THREAD

**Issue by Aleks3050** [AdaptiveConsulting/nexus-casc-plugin#4]
Hi @bdellegrazie !
I need create cleanup policy with format "All Formats"
I try to use cleanup policy format  option
```
format: "(All Formats)"
format: "all", etc
```

But no effect. I can't attach policy to repository.
What word i need to conflure for "All Formats"?
Thank you!
 (nexus 3.24)

**Comment by bdellegrazie** [comment]
Hi @Aleks3050,

The constants for the various values are in the public code:
https://github.com/sonatype/nexus-public/blob/release-3.24.0-02/components/nexus-cleanup-config/

the value you need is `ALL_FORMATS`. I have added an example.

In addition you should upgrade to 3.25.1 for security reasons.

Thanks!

**Comment by Aleks3050** [comment]
Thank you!
