### ISSUE TITLE
http(s) connector port for docker repository

### ISSUE THREAD

**Issue by Aleks3050** [AdaptiveConsulting/nexus-casc-plugin#5]
Hi @bdellegrazie  !
Please tell me how to configure http(s) connector for docker group?
![Screenshot_12](https://user-images.githubusercontent.com/27858401/91221948-2644b800-e727-11ea-9e83-f42ca6fde87c.png)

Thank you!

**Comment by Aleks3050** [comment]
And second question - how to use option "Use Docker Hub"?
![Screenshot_13](https://user-images.githubusercontent.com/27858401/91225519-678b9680-e72c-11ea-9af9-34a1f23af81d.png)
Thank you!

**Comment by bdellegrazie** [comment]
Hi @Aleks3050 ,

For the first question:
Use `httpPort` and `httpsPort` respectively in the attributes/docker section. A commented out example has been added to the sample:
https://github.com/AdaptiveConsulting/nexus-casc-plugin/blob/970de38632fccab768e0c9c8d44d24156557024b/default-nexus.yml#L177-L178

For the second question there is an existing example in the sample:
The key elements are `v1Enabled: true`, `remoteUrl: https://registry-1.docker.io` and `indexType: HUB`
https://github.com/AdaptiveConsulting/nexus-casc-plugin/blob/970de38632fccab768e0c9c8d44d24156557024b/default-nexus.yml#L186-L217
